"""Initial migration

Revision ID: 61171c432bd7
Revises: 2b250be4a415
Create Date: 2024-08-29 23:44:49.665644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61171c432bd7'
down_revision = '2b250be4a415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beddb', schema=None) as batch_op:
        batch_op.alter_column('bed_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('floor_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('floordb', schema=None) as batch_op:
        batch_op.alter_column('floor_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['floor_count'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('floordb', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('floor_count',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('beddb', schema=None) as batch_op:
        batch_op.alter_column('floor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('bed_number',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
