"""empty message

Revision ID: cac3d335705c
Revises: 
Create Date: 2024-08-26 16:56:37.835285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cac3d335705c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('floordb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('floor_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('phn_no', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('blood_group', sa.Text(), nullable=True),
    sa.Column('fathers_name', sa.Text(), nullable=True),
    sa.Column('can_view_records', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('phn_no', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('blood_group', sa.Text(), nullable=True),
    sa.Column('fathers_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beddb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bed_number', sa.Integer(), nullable=True),
    sa.Column('is_allotted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('allotted_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['floor_id'], ['floordb.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beddb')
    op.drop_table('patient_profile')
    op.drop_table('patient_details')
    op.drop_table('floordb')
    # ### end Alembic commands ###
